shellEmulator: true

trustPolicy: no-downgrade

packages:
  - playground
  - docs
  - packages/*
  - examples/*

catalogs:
  cli:
    '@antfu/eslint-config': ^6.7.3
    '@antfu/ni': ^28.0.0
    '@modelcontextprotocol/inspector': ^0.18.0
    bumpp: ^10.3.2
    eslint: ^9.39.2
    lint-staged: ^16.2.7
    nodemon: ^3.1.11
    simple-git-hooks: ^2.13.1
    tsx: ^4.21.0
    typescript: ~5.9.3
    unbuild: ^3.6.1
    vite: ^7.3.0
    vue-tsc: ^3.2.1
  nuxt:
    '@nuxt/devtools': ^3.1.1
    '@nuxt/eslint-config': ^1.12.1
    '@nuxt/kit': ^4.2.2
    '@nuxt/module-builder': ^1.0.2
    '@nuxt/schema': ^4.2.2
    '@nuxt/test-utils': ^3.21.0
    nitropack: ^2.12.9
    nuxi: ^3.31.3
    nuxt: ^4.2.2
  prod:
    '@modelcontextprotocol/sdk': ^1.25.1
    ansis: ^4.2.0
    async-cache-dedupe: ^3.4.0
    citty: ^0.1.6
    debug: ^4.4.3
    h3: ^1.15.4
    pathe: ^2.0.3
    unimport: ^5.6.0
    zod: ^3.25.76
  testing:
    vitest: ^4.0.16
    vitest-package-exports: ^1.1.1
    yaml: ^2.8.2
  types:
    '@types/debug': ^4.1.12
    '@types/node': latest
  utils:
    '@antfu/utils': ^9.3.0
    tinyexec: ^1.0.2

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - simple-git-hooks
  - unrs-resolver
